version: '3.8'

x-environment-variables:
  &default-environment
  REDIS_PORT: 6379
  REDIS_HOST: redis
  LOG_LEVEL: INFO
  EVENT_SERVICE_URL: http://event_logger:5000

services:
  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    environment:
      <<: *default-environment

  event_logger:
    build:
      context: ./src/
      dockerfile: Dockerfile
    environment:
      <<: *default-environment
    ports:
      - "5000:5000"
    volumes:
      - ./info.log:/app/info.log
    depends_on:
      - redis

  notification_processor:
    build:
      context: ./src/
      dockerfile: Dockerfile
    command: celery -A notification_processor worker --loglevel=info
    environment:
      <<: *default-environment
    depends_on:
      - redis

  flower:
    build: ./src/
    command: celery -A notification_processor flower
    ports:
      - 5555:5555
    environment:
      <<: *default-environment
    depends_on:
      - redis
      - notification_processor